### ISSUE TITLE
Leaf Issues

### ISSUE THREAD

**Issue by CaptGates** [GotoLink/NatureOverhaul#2]
I'm currently running the newest Direwolf20 pack on FTB with Mekanism and Nature Overhaul added.  The issue I'm running into is leaves are changing into different types of leaves and even into berry bushes.  I was looking in the config file trying to figure it out and from what I can tell in the misc options it's populating information wrong.  Here's a pastebin of affected part http://pastebin.com/KeSDdbdV.

Not sure if it's in issue with Nature Overhaul or the other mods.

**Comment by GotoLink** [comment]
This is actually because NatureOverhaul has no way to tell which sapling block will produce the trunk and leaves blocks.
This configuration mitigates the issue by providing user control.
Let's take the first line:
minecraft:sapling(0)-minecraft:log(0,4,8,12)-minecraft:leaves(0,4,8,12)
Actually represent an "oak tree logic": oak sapling - oak logs (different rotations) - oak leaves (different  decaying states)

Lines as such:
Natura:florasapling(4)-Natura:tree(0,4,8,12)-Natura:BerryBush(0,4,8,12)
Are doing the "leaves changing into berry bushes" bug.
I would replace "BerryBush" with "floraleaves".

**Comment by CaptGates** [comment]
I was looking at the TreeData.java and was trying to understand how it was pulling the info.  I get your example and figured I'd have to go in and change each one manully.  Is there anyway to know which leaves there are without going into each seperate mod to find them?

For this line:
Natura:Rare Sapling(7)-Natura:willow(3,7,11,15)-Natura:NetherBerryBush(3,7,11,15)

Besides going through the Natura code is there anyway to know that the Rare sapling is the willow and if there are willow leaves?  The fix I'm testing now is just not to have trees die and from what I can see the leaf death and growth spits out saplings.

Thanks for the quick reply and keeping these mods going.  I've been trying to find one like Nature Overhaul for a while now and just found this yesterday.

**Comment by GotoLink** [comment]
From this config file, Natura has at least 4 leaves block readily compatible with NatureOverhaul:
Natura:floraleaves
Natura:floraleavesnocolor
Natura:Dark Leaves
Natura:Rare Leaves
I have no idea if any of those could/should be attached to a "willow tree" or not.

You probably should remove the lines with TConstruct:ore.berries, too.

Anyway, i am working on some clever tree detection, to hopefully improve the default values.

**Comment by CaptGates** [comment]
After spending the last 3 hours and only getting half of natura's trees working I can admit I'm in over my head here.  I'll have to wait and see how the new tree detection works out.  If I just leave all the modded trees out of the config will it then only affect the vanilla trees so I can still get some effect out of the mod?

**Comment by GotoLink** [comment]
Yes if you leave only the first six lines about vanilla blocks, it should be fine.

**Comment by CaptGates** [comment]
That was a quick turn around, I was expecting to be waiting for at least a couple weeks.  Not sure what you test with however just looking at the new config for the Direwolf20 pack, http://pastebin.com/npsEgR2s its definitely looking a lot cleaner and lined up.

Only issue I ran into so far is it took a while for it to run.  One first creating the world instead of loading up it would create the world and then shut down the internal server and go back to the main menu.  Then when reloading the world it would kind of freeze up on the loading screen and say it was shutting down the server but then after maybe 5 minutes finally load up for me.

Thanks for the quick update on it though and I'll let you know if I run into anymore issues.

**Comment by GotoLink** [comment]
I had this design in mind from a long time ago. The actual implementation went smoother than expected.

Yes, this will take a bit longer the first time a world is loaded. Even more so for each mod that adds saplings.
Anyway, i just added a quick patch to lower the load time.
If there is any crash, please publish the report in a new issue.
