### ISSUE TITLE
RotaryCraft conflict cfg NatureOverhaul

### ISSUE THREAD

**Issue by SvEgiiVEteR** [GotoLink/NatureOverhaul#3]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/737
log
https://gist.github.com/ebc77a8fbc348de72c70f8a3c0f9ab5c
line 4058

**Comment by ReikaKalseki** [comment]
NatureOverhaul clearly autogenerates this config, but from what?

**Comment by SvEgiiVEteR** [comment]
@ReikaKalseki 
when I put RotaryCraft
in Nature Overhaul config added 2 lines that break down configuration.
`Spreading {
# [default: 0]
I:=0
and
Flammability {
# [default: 0]
I:=0`
It must be like this:
I: ACentauriBbGrunt = 0
I checked more than once.

and all my settings for performance, are reset.
It helps only manual removal I: = 0 from the config.
but after the start of the game they are added again. ((

**Comment by GotoLink** [comment]
The line that generates this config:
`config.getInt(optionsCategory[13] + ".Spreading", i.getUnlocalizedName().substring(5), Blocks.fire.getEncouragement(i)));`
All block unlocalized names start with "tile." internally, hence the substring.
I guess i'll cover the other case too.

**Comment by ReikaKalseki** [comment]
Wait, are you saying a RotaryCraft block has an unlocalized name of "tile.."? I would imagine this would have been noticed sooner.

**Comment by SvEgiiVEteR** [comment]
https://gist.github.com/2f48e0f6eada7fb43cbc5379db8707f8

Now I began to appear, such crash.
I think it's just because of the added these lines RotaryCraft
Flammability
        I:=0
Spreading
        I:=0
it is in the section fire "Fire Options"

Reika.DragonAPI.Instantiable.Event.Client.RenderBlockAtPosEvent.**fire**

**Comment by ReikaKalseki** [comment]
No, that has no relation whatsoever.

**Comment by SvEgiiVEteR** [comment]
Yes. that's another problem with simCraft.
deleted blocks from config help.

about I:=0 :
I do so
"% BINDIR% .minecraft \ config \ natureoverhaulBP.cfg" "% BINDIR% .minecraft \ config \ natureoverhaul.cfg"
after creating a config copy in natureoverhaulBP.cfg and removes:
I:=0
temporary solution...

**Comment by SvEgiiVEteR** [comment]
@ReikaKalseki @GotoLink 
what to do with strings I:=0
which is created due to RotaryCraft

tired to remove them each time in the manual of config ... ((

**Comment by ReikaKalseki** [comment]
I still wonder what was empty; checking has not shown any empty-string unlocalized names in RotaryCraft, at least in the dev environment.

**Comment by SvEgiiVEteR** [comment]
@GotoLink thanks now no problems)
